pipeline {
    agent { dockerfile {
          dir 'jenkins/stock-synthesis/model'
        }
    }
    stages {
		stage('clean up from previous run') {
		    steps {
		        sh label: 'remove an old dir (force in case does not exist)', script: 'rm -rf ss_bin'
			}
		}
	    stage('move shell script') {
		    steps{
			    sh label: 'remove an old file (force in case does not exist)', script: 'rm -f run_models_2.sh'
			    sh label: 'copy over new version', script: 'cp jenkins/stock-synthesis/model/run_models_2.sh run_models_2.sh'
				sh label: 'Make executable', script: 'chmod a+x run_models_2.sh'  
			}
		}
        stage('Copy ss.gz artifact from previous stage') {
            steps {
              copyArtifacts filter: 'ss.gz', fingerprintArtifacts: true, projectName: 'stock-synthesis-build', selector: lastSuccessful()
			}
        }
        stage('Git clone src for stock synthesis Example files') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '1aa2d7c8-749f-4270-9de2-6ffcf0cd2beb', url: 'https://stock_synthesis.build@vlab.ncep.noaa.gov/git/ss_examples']]])
            }
        }
        stage('Unpack ss.gz artifact') {
            steps {
                sh label: 'Remove ss if exists', script: 'rm ss | true'
                sh label: 'Unzip ss', script: 'gunzip ss.gz'
                sh label: 'Make ss executable', script: 'chmod a+rwx ss'
				sh label: 'make ss executable folder', script: 'mkdir ss_bin'
				sh label: 'Move ss executable', script: 'mv ss ss_bin/ss'
                sh label: 'Get dir listing', script: 'ls -alh *'
            }
        }
		stage('Run ss on models') {
            steps {
                //sh label: 'Copy ss to Simple', script: 'cp ss Simple/'
				sh label: 'Put SS in path and run models', script: '/bin/bash ./run_models_2.sh'
            }
        }
    }
    post {
	    always {
		    steps {
				sh label: 'Remove models.zip if exists', script: 'rm models.zip | true'
                sh label: 'Zip models folder', script: 'zip models.zip models/*'
                archiveArtifacts 'models.zip'
            }
		}
        failure {
            mail bcc: '', body: 'Stock Synthesis build failed.', cc: '', from: '', replyTo: '', subject: 'stock-synthesis-model: Jenkins Build Failure', to: 'kathryn.doering@noaa.gov'
        }
        changed {
            script {
                if (currentBuild.currentResult == 'SUCCESS') { // Other values: SUCCESS, UNSTABLE
                    // Send an email only if the build status has changed from red to green
                   mail bcc: '', body: 'Stock Synthesis build now passing!', cc: '', from: '', replyTo: '', subject: 'stock-synthesis-model: Jenkins Build Passing Again', to: 'kathryn.doering@noaa.gov'
                }
            }
        }
    }
}