pipeline {
    agent { dockerfile {
          dir 'jenkins/stock-synthesis/build-linux'
          args '-u 0:0'
        }
    }
    stages {
        stage('Git clone src for stock-synthesis') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'vlab/stock-synthesis']], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '1aa2d7c8-749f-4270-9de2-6ffcf0cd2beb', url: 'https://stock_synthesis.build@vlab.ncep.noaa.gov/git/stock-synthesis']]])
            }
        }
        stage('Build SS safe executable') {
            steps {
                sh label: 'Make build script executable', script: 'cd vlab/stock-synthesis && chmod a+x Make_SS_330_new.sh'
                sh label: 'Run build', script: 'cd vlab/stock-synthesis && ./Make_SS_330_new.sh -b SS330 -a /usr/local/bin/admb'
                
                //sh label: 'Make build script executable', script: 'cd vlab/stock-synthesis && chmod a+x Make_SS_330.sh'
                //sh label: 'Run build', script: 'cd vlab/stock-synthesis && ls && export BUILD_DIR="SS330" && ./Make_SS_330.sh'
                //sh label: 'Validate build', script: 'cp vlab/stock-synthesis/SS330/ss . && sha256sum ss'
            }
        }
        stage('Build SS opt executable')  {
            steps{
                sh label: 'Dummy option: see dir contents', script: 'ls'
                // sh label: 'Make build script executable', script: 'cd vlab/stock-synthesis && chmod a+x Make_SS_330_opt.sh'
                //sh label: 'Run build', script: 'cd vlab/stock-synthesis && ls && export BUILD_DIR="SS330" && ./Make_SS_330_opt.sh'
                //sh label: 'Validate build', script: 'cp vlab/stock-synthesis/SS330/ss_opt . && sha256sum ss_opt'         
           }   
        }
        stage('Build SS trans executable')  {
            steps {
                   sh label: 'Dummy option: see dir contents', script: 'ls'
                // sh label: 'Make build script executable', script: 'cd vlab/stock-synthesis && chmod a+x Make_SS_transition.sh'
                // sh label: 'Run build', script: 'cd vlab/stock-synthesis && ls && export BUILD_DIR="SS330_tr" && ./Make_SS_transition.sh'
                // sh label: 'Validate build', script: 'cp vlab/stock-synthesis/SS330_tr/ss_trans . && sha256sum ss_trans'          
           }
        }
        stage('Archive artifact') {
            steps {
                archiveArtifacts 'vlab/stock-synthesis/SS330/ss'
                // archiveArtifacts 'vlab/stock-synthesis/SS330/ss, vlab/stock-synthesis/SS330/ss.tpl, vlab/stock-synthesis/SS330/ss_opt, vlab/stock-synthesis/SS330_tr/ss_trans'
            }
        }
    }
	post {
		failure {
			mail bcc: '', body: 'The job Stock-Synthesis-build-linux failed.', cc: '', from: '', replyTo: '', subject: 'stock-synthesis-build: Jenkins Build Failure', to: 'kathryn.doering@noaa.gov'
		}
		changed {
			script {
				if (currentBuild.currentResult == 'SUCCESS') { // Other values: SUCCESS, UNSTABLE
					// Send an email only if the build status has changed from failure to success
				   mail bcc: '', body: 'The job Stock-Synthesis-build-linux is now passing.', cc: '', from: '', replyTo: '', subject: 'stock-synthesis-build: Jenkins Build Passing Again', to: 'kathryn.doering@noaa.gov'
				}
			}
		}
    }
}