pipeline {
    agent { dockerfile {
          dir 'jenkins/stock-synthesis/simple-model'
        }
    }
    stages {
        stage('Copy ss.gz artifact from previous stage') {
            steps {
              copyArtifacts filter: 'ss.gz', fingerprintArtifacts: true, projectName: 'stock-synthesis-build', selector: lastSuccessful()
            }
        }
        stage('Git clone src for stock synthesis Example files') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '1aa2d7c8-749f-4270-9de2-6ffcf0cd2beb', url: 'https://stock_synthesis.build@vlab.ncep.noaa.gov/git/ss_examples']]])
            }
        }
        stage('Unpack ss.gz artifact') {
            steps {
                sh label: 'Remove ss if exists', script: 'rm ss | true'
                sh label: 'Unzip ss', script: 'gunzip ss.gz'
                sh label: 'Make ss executable', script: 'chmod a+rwx ss'
                sh label: 'Get dir listing', script: 'ls -alh *'
            }
        }
        stage('Run ss on Simple/ model') {
            steps {
                sh label: 'Copy ss to Simple', script: 'cp ss Simple/'
                sh label: 'Run ss on Simple', script: 'cd Simple && ./ss'
                sh label: 'Get dir listing', script: 'ls -alh *'
            }
        }
        stage('Zip and Archive') {
            steps {
                sh label: 'Remove Simple.zip if exists', script: 'rm Simple.zip | true'
                sh label: 'Zip Simple folder', script: 'zip Simple.zip Simple/*'
                archiveArtifacts 'Simple.zip'
            }
        }

    }
    post {
        failure {
            mail bcc: '', body: 'Stock Synthesis build failed.', cc: '', from: '', replyTo: '', subject: 'stock-synthesis-model: Jenkins Build Failure', to: 'kathryn.doering@noaa.gov richard.methot@noaa.gov ian.taylor@noaa.gov'
        }
        changed {
            script {
                if (currentBuild.currentResult == 'SUCCESS') { // Other values: SUCCESS, UNSTABLE
                    // Send an email only if the build status has changed from red to green
                   mail bcc: '', body: 'Stock Synthesis build now passing!', cc: '', from: '', replyTo: '', subject: 'stock-synthesis-model: Jenkins Build Passing Again', to: 'kathryn.doering@noaa.gov richard.methot@noaa.gov ian.taylor@noaa.gov'
                }
            }
        }
    }
}