pipeline {
    agent { dockerfile {
          dir 'jenkins/mcmc'
        }
    }
    stages { 
	    stage('Prepare workspace') {
            steps {
			  sh label: 'print wd', script: 'pwd'
			  sh label: 'view files', script: 'ls .'
			  sh label: 'remove an old file (force in case does not exist)', script: 'rm -f models.zip'
			  sh label: 'remove an old dir (force in case does not exist)', script: 'rm -rf ss_bin'
			  sh label: 'remove an old dir (force in case does not exist)', script: 'rm -rf run_R'
			  sh label: 'verify removed', script: 'ls .'
		   }
        }
        stage('Copy models.zip artifact from previous stage') {
            steps {
			  sh label: 'create subfolder to save artifact', script: 'mkdir run_R'
              copyArtifacts filter: 'models.zip', fingerprintArtifacts: true, projectName: 'stock-synthesis-model', selector: lastSuccessful()
              sh label: 'move models.zip', script: 'mv models.zip run_R/models.zip' 
			  sh label: 'Unzip models.zip', script: 'cd run_R && unzip models.zip'
		   }
        }
		stage('Copy and unpack ss.gz artifact from previous stage') {
            steps {
              copyArtifacts filter: 'ss.gz', fingerprintArtifacts: true, projectName: 'stock-synthesis-build', selector: lastSuccessful()
			  sh label: 'Unzip ss', script: 'gunzip ss.gz'
              sh label: 'Make ss executable', script: 'chmod a+rwx ss'
			  sh label: 'Move ss executable', script: 'mv ss run_R/model_runs/Simple/ss'
			}
        }
	    stage('Run R code') {
		    steps{
		    	sh label: 'install and run r code', script: 'cd run_R/model_runs/Simple && Rscript ~/var/lib/jenkins/workspace/stock-synthesis-mcmc/jenkins/mcmc/run_mcmc.R'
			}
		}
	}
	post {
		failure {
			mail bcc: '', body: 'Stock Synthesis build failed.', cc: '', from: '', replyTo: '', subject: 'Jenkins Build Failure: stock-synthesis-mcmc', to: 'kathryn.doering@noaa.gov'
		}
	}	
}