pipeline {
    agent { dockerfile {
          dir 'jenkins/build-linux'
          args '-u 0:0'
        }
    }
    stages {
        stage('Make folder to store archives')  {
            steps{
			    sh label: 'view workspace', script: 'ls -l'
                sh label: 'remove old build dir (force in case does not exist)', script: 'rm -rf builds'
                sh label: 'make directory', script: 'mkdir builds'
				sh label: 'remove old SS330 dir (force in case does not exist)', script: 'rm -rf SS330'
				sh label: 'make SS330 directory', script: 'mkdir SS330'
            }
        }
        stage('Build SS safe executable') {
            steps {
                sh label: 'confirm build script executable', script: 'cd vlab/stock-synthesis && ls -l'
                sh label: 'Run build', script: 'cd vlab/stock-synthesis && /bin/bash ./Make_SS_330_new.sh -b SS330 -a /usr/local/admb-12.2'
                sh label: 'Validate build', script: 'cp SS330/ss . && sha256sum ss'
                sh label: 'Make build executable', script: 'chmod a+x SS330/ss'  
                sh label: 'Move build to archive folder', script: 'mv SS330/ss  builds/ss'    
                sh label: 'Copy tpl to archive folder', script: 'mv SS330/ss.tpl  builds/ss.tpl'                 
            }
        }
        stage('Build SS opt executable')  {
            steps {
                sh label: 'Run build', script: 'cd vlab/stock-synthesis && /bin/bash ./Make_SS_330_new.sh -b SS330 -a /usr/local/admb-12.2 -o'
                sh label: 'Validate build', script: 'cp SS330/ss_opt . && sha256sum ss_opt' 
                sh label: 'Make build executable', script: 'chmod a+x SS330/ss_opt'   
                sh label: 'Move build to archive folder', script: 'mv SS330/ss_opt  builds/ss_opt'                    
            }   
        }
        stage('Build SS trans executable')  {
            steps {
                sh label: 'Run build', script: 'cd vlab/stock-synthesis && /bin/bash ./Make_SS_330_new.sh -b SS330 -a /usr/local/admb-12.2 -t'
                sh label: 'Validate build', script: 'cp SS330/ss_trans . && sha256sum ss_trans'   
                sh label: 'Make build executable', script: 'chmod a+x SS330/ss_trans'     
                sh label: 'Copy build to archive folder', script: 'mv SS330/ss_trans  builds/ss_trans'                   
                sh label: 'Check build permissions', script: 'cd builds && ls -l'
           }
        }
    }
	post {
        always {
            archiveArtifacts 'builds/*'
        }
		failure {
			mail bcc: '', body: 'The job Stock-Synthesis-build-linux failed.', cc: '', from: '', replyTo: '', subject: 'stock-synthesis-build: Jenkins Build Failure', to: 'kathryn.doering@noaa.gov'
		}
		changed {
			script {
				if (currentBuild.currentResult == 'SUCCESS') { // Other values: SUCCESS, UNSTABLE
					// Send an email only if the build status has changed from failure to success
				   mail bcc: '', body: 'The job Stock-Synthesis-build-linux is now passing.', cc: '', from: '', replyTo: '', subject: 'stock-synthesis-build-linux: Jenkins Build Passing Again', to: 'kathryn.doering@noaa.gov'
				}
			}
		}
    }
}