FROM rocker/r-ver
MAINTAINER FRAM Data Team <nmfs.nwfsc.fram.data.team@noaa.gov>

RUN apt-get update
RUN chmod 777 /usr/local/lib/R/site-library
RUN apt-get -y install libxml2-dev
RUN apt-get -y install libcurl4-openssl-dev