pipeline {
    agent { dockerfile {
          dir 'jenkins/stock-synthesis/r4ss'
        }
    }
    stages { 
	    stage('Prepare workspace') {
            steps {
			  sh label: 'print wd', script: 'pwd'
			  sh label: 'view files', script: 'ls .'
			  sh label: 'remove an old dir (force in case does not exist)', script: 'rm -rf simple_run'
			  sh label: 'remove an old file (force in case does not exist)', script: 'rm -f Simple.zip'
			  sh label: 'remove an old file (force in case does not exist)', script: 'rm -rf local_R_lib'
			  sh label: 'verify removed', script: 'ls .'
		   }
        }
        stage('Copy Simple.zip artifact from previous stage') {
            steps {
			  sh label: 'create subfolder to save artifact', script: 'mkdir simple_run'
              copyArtifacts filter: 'Simple.zip', fingerprintArtifacts: true, projectName: 'stock-synthesis-model', selector: lastSuccessful()
			  sh label: 'view files', script: 'ls .'
              sh label: 'move Simple.zip', script: 'mv Simple.zip simple_run/Simple.zip' 
			  sh label: 'verify move', script: 'cd simple_run && ls .'
			  sh label: 'Unzip Simple.zip', script: 'cd simple_run && unzip Simple.zip'
			  sh label: 'view files', script: 'ls .'
		   }
        }
	    stage('Run R code to test R') {
		    steps{
			    sh label: 'view files and str', script: 'ls /usr/local/lib/R -l'
				sh label: 'create a dir for local r lib', script: 'mkdir local_R_lib'
		    	sh label: 'install and run r4ss', script: 'Rscript jenkins/stock-synthesis/r4ss/run_r4ss.R'
			}	
		}
	}
    post {
	    always {
		    archiveArtifacts 'simple_run/Simple/plots/*'
		}
        failure {
            mail bcc: '', body: 'Stock Synthesis build failed.', cc: '', from: '', replyTo: '', subject: 'Jenkins Build Failure: stock-synthesis-r4ss', to: 'kathryn.doering@noaa.gov '
        }
        changed {
            script {
                if (currentBuild.currentResult == 'SUCCESS') { // Other values: SUCCESS, UNSTABLE
                    // Send an email only if the build status has changed from red to green
                   mail bcc: '', body: 'Stock Synthesis build now passing!', cc: '', from: '', replyTo: '', subject: 'Jenkins Build Passing Again: stock-synthesis-r4ss', to: 'kathryn.doering@noaa.gov'
                }
            }
        }
    }
}