# Get ss3 releases and run test model with estimation and hessian
name: run-releases-with-test-model
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 15 * * 2' # every Tuesday at 3pm UTC (= 1 0am EST or 11am EDT Eastern time)


# Run fast running SS3 test models with estimation
jobs:
  run-releases-with-test-model:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest}
          - {os: macos-13}
          - {os: macos-latest}
          - {os: ubuntu-latest}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:

      - name: Checkout models repo
        uses: actions/checkout@v4
        with:
          repository: 'nmfs-ost/ss3-test-models'
          path: test-models-repo

      - name: Update Ubuntu packages
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install --only-upgrade libstdc++6
          sudo apt install libc6
          sudo apt-get install -y libcurl4-openssl-dev
          sudo apt install libfontconfig1-dev
          
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install r4ss and run test model on two_morph_seas_areas model
        run: |
          install.packages(c("remotes", "svglite", "systemfonts"), dependencies = TRUE)
          remotes::install_github("r4ss/r4ss", ref = "more-gh-fixes-for-gha")
          library(r4ss)
          dir <- file.path(getwd(), "test-models-repo", "models", "two_morph_seas_areas")
          r4ss::get_ss3_exe(dir = dir)
          r4ss::run(dir = dir)
          r4ss::SS_output(dir, verbose = TRUE)
        shell: Rscript {0}


