name: docker-windows

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@main
    - name: run
      run: |
        C:\Program\ Files\Docker\Docker\DockerCli.exe -SwitchLinuxEngine
        docker pull johnoel/admb:linux
        make docker
