name: docker-macos

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@main
    - name: run
      run: |
        docker pull johnoel/admb:linux
        make docker
