pipeline {
    agent { dockerfile {
          dir 'jenkins/stock-synthesis/compare'
        }
    }
    stages { 
	    stage('Prepare workspace') {
            steps {
			  sh label: 'print wd', script: 'pwd'
			  sh label: 'view files', script: 'ls .'
			  sh label: 'remove an old dir (force in case does not exist)', script: 'rm -rf Simple'
			  sh label: 'remove an old dir (force in case does not exist)', script: 'rm -rf simple_run'
			  sh label: 'remove an old dir (force in case does not exist)', script: 'rm -rf ss_example_files'
			  sh label: 'remove an old dir (force in case does not exist)', script: 'rm -rf run_R'
			  sh label: 'remove an old file (force in case does not exist)', script: 'rm -f Simple.zip'
			  sh label: 'remove an old file (force in case does not exist)', script: 'rm -f models.zip'
			  sh label: 'remove an old file (force in case does not exist)', script: 'rm -f rename_ref_files.sh'
			  sh label: 'verify removed', script: 'ls .'
		   }
        }
	    stage('move shell script') {
		    steps{
			    sh label: 'copy over new version', script: 'cp jenkins/stock-synthesis/compare/rename_ref_files.sh rename_ref_files.sh'
				sh label: 'Make executable', script: 'chmod a+x rename_ref_files.sh'  
			}
		}
        stage('Copy models.zip artifact from previous stage') {
            steps {
			  sh label: 'create subfolder to save artifact', script: 'mkdir run_R'
              copyArtifacts filter: 'models.zip', fingerprintArtifacts: true, projectName: 'stock-synthesis-model', selector: lastSuccessful()
			  sh label: 'view files', script: 'ls .'
              sh label: 'move models.zip', script: 'mv models.zip run_R/models.zip' 
			  sh label: 'verify move', script: 'cd run_R && ls .'
			  sh label: 'Unzip models.zip', script: 'cd run_R && unzip models.zip'
			  sh label: 'view files', script: 'ls -R run_R'
		   }
        }
        stage('Git clone src for stock synthesis reference run files') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '1aa2d7c8-749f-4270-9de2-6ffcf0cd2beb', url: 'https://stock_synthesis.build@vlab.ncep.noaa.gov/git/ss_examples']]])
			}
        }
		stage('set up stock synthesis reference run files') {
		    steps {
			    sh label: 'view files', script: 'ls .'
				sh label: 'create subfolder to move repo files', script: 'mkdir ss_example_files'
				sh label: 'move the repo Simple files', script: 'mv models ss_example_files'
				sh label: 'view files', script: 'ls .'
				sh label: 'view files', script: 'cd ss_example_files && ls -R .'
				sh label: 'rename files', script: './rename_ref_files.sh'
				sh label: 'view renamed files', script: 'cd ss_example_files && ls -R .'
			}
		}
	    stage('Run test R script') {
		    steps{
			    sh label: 'test R code', script: 'Rscript run_compare.R'
			}	
		}
		stage('Determine results of test') {
		    steps{
			    sh label: 'run R code', script: 'Rscript check_failed.R'
			}
		}
	}
    post {
	    always {
		    archiveArtifacts 'run_R/compare_test.txt'
		}
        failure {
            mail bcc: '', body: 'Stock Synthesis build failed.', cc: '', from: '', replyTo: '', subject: 'Jenkins Build Failure: stock-synthesis-compare', to: 'kathryn.doering@noaa.gov'
        }
        changed {
            script {
                if (currentBuild.currentResult == 'SUCCESS') { // Other values: SUCCESS, UNSTABLE
                    // Send an email only if the build status has changed from red to green
                   mail bcc: '', body: 'Stock Synthesis build now passing!', cc: '', from: '', replyTo: '', subject: 'Jenkins Build Passing Again: stock-synthesis-compare', to: 'kathryn.doering@noaa.gov'
                }
            }
        }
    }
}